/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package braintease;
import java.sql.*;
import sqlConnect.ConnectionProvider;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sarina
 */
public class Addition extends javax.swing.JFrame {

    /**
     * Creates new form Addition
     */
    public Addition() {
        initComponents();
        this.setLocationRelativeTo(null);
       /* try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            
            int n=st.executeUpdate("");
        }
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Question = new javax.swing.JTextField();
        Answer = new javax.swing.JTextField();
        Option1 = new javax.swing.JTextField();
        Option2 = new javax.swing.JTextField();
        Option3 = new javax.swing.JTextField();
        Option4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Minimize = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Qno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 25, 0, 0));
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Kokonor", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add new question.png"))); // NOI18N
        jLabel1.setText("ADD NEW QUESTION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 480, 60));

        jLabel3.setFont(new java.awt.Font("Kailasa", 1, 18)); // NOI18N
        jLabel3.setText("Answer :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 100, -1));

        jLabel4.setFont(new java.awt.Font("Kailasa", 1, 18)); // NOI18N
        jLabel4.setText("Question no. : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 140, -1));

        jLabel5.setFont(new java.awt.Font("Kailasa", 1, 18)); // NOI18N
        jLabel5.setText("Question : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 160, -1));

        jLabel6.setFont(new java.awt.Font("Kailasa", 1, 18)); // NOI18N
        jLabel6.setText("Option 1 : ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 100, -1));

        jLabel7.setFont(new java.awt.Font("Kailasa", 1, 18)); // NOI18N
        jLabel7.setText("Option 2 : ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 100, -1));

        jLabel8.setFont(new java.awt.Font("Kailasa", 1, 18)); // NOI18N
        jLabel8.setText("Option 3 : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 100, -1));

        jLabel10.setFont(new java.awt.Font("Kailasa", 1, 18)); // NOI18N
        jLabel10.setText("Option 4 : ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 100, -1));
        jPanel1.add(Question, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 580, 60));
        jPanel1.add(Answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 580, -1));
        jPanel1.add(Option1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 580, -1));
        jPanel1.add(Option2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 580, -1));
        jPanel1.add(Option3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 580, -1));
        jPanel1.add(Option4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 580, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton1.setText("SAVE");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 490, 120, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 120, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Back.png"))); // NOI18N
        jButton3.setText("Back to Home");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, 30));

        Minimize.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Minimize.setText("-");
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });
        jPanel1.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 30, 40));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel11.setText("X");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 30, 40));
        jPanel1.add(Qno, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 60, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 922, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Question.setText("");
        Option1.setText("");
        Option2.setText("");
        Option3.setText("");
        Option4.setText("");
        Answer.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String qno=Qno.getText();
        String q=Question.getText();
        String option1=Option1.getText();
        String option2=Option2.getText();
        String option3=Option3.getText();
        String option4=Option4.getText();
        String answer=Answer.getText();
        try {
            validateOption();
            try{
                Connection con=ConnectionProvider.getCon();
                PreparedStatement ps= con.prepareStatement("insert into questions values(?,?,?,?,?,?,?)");
                ps.setString(1,qno);
                ps.setString(2,q);
                ps.setString(3,option1);
                ps.setString(4,option2);
                ps.setString(5,option3);
                ps.setString(6,option4);
                ps.setString(7,answer);
                ps.executeUpdate();
                JFrame jf=new Jframe();
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf,"Successfully Updated");
                Addition a2=new Addition();
                a2.setVisible(true);
                this.dispose();
            } catch(Exception e){
                JFrame jf=new Jframe();
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf,e);
            }
        } catch (MissingFieldsException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill all the fields!");
        }
               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        AdminPage h=new AdminPage();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeMouseClicked

    private void validateOption() throws MissingFieldsException {
        if (Question.getText().isEmpty() || Option1.getText().isEmpty() || Option2.getText().isEmpty() || Option3.getText().isEmpty() || Option4.getText().isEmpty()) {
            throw new MissingFieldsException("Missing text in fields.");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addition().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Answer;
    private javax.swing.JLabel Minimize;
    private javax.swing.JTextField Option1;
    private javax.swing.JTextField Option2;
    private javax.swing.JTextField Option3;
    private javax.swing.JTextField Option4;
    private javax.swing.JTextField Qno;
    private javax.swing.JTextField Question;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public class MissingFieldsException extends Exception {
        public MissingFieldsException(String str) {
            super(str);
        }
    }
    
    private static class Jframe extends JFrame {

        public Jframe() {
        }
    }
}
